### ISSUE TITLE
Backport of per-user-slice resource-control to v234

### ISSUE THREAD

**Issue by dev-zero** [openSUSE/systemd#15]
**Is your feature request related to a problem? Please describe.**

Since Leap 15.2 seems to be using v234 still, it would be really nice if the per-user-slice resource-control from systemd v240+ could be backported. At the moment [direct manipulation of the cgroups is required](https://unix.stackexchange.com/a/452734) to limit resources for users, or [a 3rdparty PAM plugin](https://github.com/BYUHPC/uft) needs to be installed.

**Describe the solution you'd like**

Ideally the backport of the respective feature from systemd v240+

**Describe alternatives you've considered**

Alternatives are given above: one requires direct manipulation of the cgroup tree, the other one a 3rdparty PAM plugin and/or specific configuration of the SSH daemon.

**Comment by fbuihuu** [comment]
Leap 15.2 is no mo supported and Leap 15.3 should have the relevant feature, hence closing.
