### ISSUE TITLE
Setting MemorySwapMax=0 for user slices ignored while it shouldn't

### ISSUE THREAD

**Issue by dev-zero** [openSUSE/systemd#16]
**systemd version the issue has been seen with**

234-lp150.20.15.1

**Used distribution**

openSUSE Leap 15.0

**Expected behaviour you didn't see**

Setting `MemorySwapMax=0B` in `user.slice` should set `memory.swap.max=0`

**Unexpected behaviour you saw**

```
Oct 23 11:08:31 myhost systemd[1]: /etc/systemd/system/user-7184.slice:3: Memory limit '0B' out of range. Ignoring.
Oct 23 11:08:31 myhost systemd[1]: /etc/systemd/system/user-7184.slice:2: Failed to assign slice user.slice to unit user-7184.slice. Ignoring.
Oct 23 11:08:31 myhost systemd[1]: /etc/systemd/system/user-7184.slice:3: Memory limit '0B' out of range. Ignoring.
Oct 23 11:08:31 myhost systemd[1]: /etc/systemd/system/user-7184.slice:2: Failed to assign slice user.slice to unit user-7184.slice. Ignoring.
```

**Steps to reproduce the problem**

With v234, create a user slice config `/etc/systemd/system/user-7184.slice`:

[Slice]
Slice=user.slice
MemorySwapMax=0B

This has been fixed upstream in https://github.com/systemd/systemd/commit/de8776316e529dc21d0140a50f348f3ff2046b52

**Comment by fbuihuu** [comment]
Can you please use https://bugzilla.suse.com/ for reporting issue as BZ is our official bug tracker ?

Thanks.
