### ISSUE TITLE
networkd: vxlan require Remote= to be a non multicast address (#8117) 

### ISSUE THREAD

**Issue by sazhufa** [openSUSE/systemd#20]
**systemd version the issue has been seen with**
> 234

**Used distribution**
 > Leap 15.1

**Expected behaviour you didn't see**
 > vxlan using Remote parameter in systemd-network 

**Unexpected behaviour you saw**
 > vxlan using Remote parameter in systemd-network says invalid multicast address.

**Steps to reproduce the problem**
skip...

There is a patch has fixed it: 
https://github.com/openSUSE/systemd/commit/bf443be99565e4327f1c8c12b79d98b4c1529cf1

Is there a plan to merge this patch into SLE15 branch ?

Thanks.

**Comment by fbuihuu** [comment]
No plan for fixing this since networkd is not supported nor even shipped by SLE.

That said the fix seems simple enough to be backported for Leap .

Can you please open a bug report via BZ instead as it's the _official_ way to report bugs against openSUSE distro ?
