### ISSUE TITLE
Please backport -D_FORTIFY_SOURCE=3 support patch

### ISSUE THREAD

**Issue by marxin** [openSUSE/systemd#42]
Please cherry-pick 0bd292567a543d124cd303f7dd61169a209cae64 to `openSUSE:Factory` package. We will need the patch for enablement of the `-D_FORTIFY_SOURCE=3` in Factory.

**Comment by fbuihuu** [comment]
Done, will be part of the next update (let me know if this needs to be submitted quickly).

**Comment by marxin** [comment]
Thank you for it. I'll need it let's say in 2 weeks from now, sooner better ;)
