### ISSUE TITLE
Please backport libbpf 1.0 support

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/systemd#63]
systemd has been finally made compatible with libbpf 1.0, which we'd like to upgrade to in tumbleweed: 

https://github.com/systemd/systemd/pull/24511

please include those patches or update systemd to a version that includes it.

**Comment by fbuihuu** [comment]
I think the easiest way to solve this is to wait until systemd v252 is released.

**Comment by fbuihuu** [comment]
v252 has been released since a couple of weeks already so I assume that this issue can be closed now.

**Comment by fbuihuu** [comment]
v252 has been released since a couple of weeks already so I assume that this issue can be closed now.
