### ISSUE TITLE
 [need help, thanks] how to set the AF_UNIX socket in /etc/crypttab?

### ISSUE THREAD

**Issue by JustPlay** [openSUSE/systemd#70]
https://github.com/openSUSE/systemd/blob/6c83054c0133eb53245e479d71589dceff76cf74/TODO#L957

based on https://www.freedesktop.org/software/systemd/man/crypttab.html

> NUL RANDOM /cryptsetup/ VOLUME
> In other words: a NUL byte (as required for abstract namespace sockets), followed by a random string (consisting of alphanumeric characters only), followed by the literal string "/cryptsetup/", followed by the name of the volume to acquire they key for. For example, for the volume "myvol":
> 
> \0d7067f78d9827418/cryptsetup/myvol

and my /etc/crypttab is

```
# <target name>        <source device>                <key file>        <options>
rootfs UUID=a5ba171f-d9a1-4874-b898-931ffd29a017 \0volcengine/cryptsetup/rootfs luks
```
but when update-initramfs, i see the following warns:
```
cryptsetup: WARNING: rootfs: keyfile 'volcengine/cryptsetup/rootfs' not found
cryptsetup: WARNING: Skipping root target rootfs: uses a key file
```

and /cryptroot/crypttab in the generated initrd.img is empty

**Comment by aafeijoo-suse** [comment]
> and my /etc/crypttab is
> 
> ```
> # <target name>        <source device>                <key file>        <options>
> rootfs UUID=a5ba171f-d9a1-4874-b898-931ffd29a017 \0volcengine/cryptsetup/rootfs luks
> ```
> 
> but when update-initramfs, i see the following warns:

`update-initramfs`? Sorry, what distro are you using, Debian/Ubuntu? SUSE does not provide `initramfs-tools`, we use [dracut](https://github.com/openSUSE/dracut) to generate initrds.

> 
> ```
> cryptsetup: WARNING: rootfs: keyfile 'volcengine/cryptsetup/rootfs' not found
> cryptsetup: WARNING: Skipping root target rootfs: uses a key file
> ```
> 
> and /cryptroot/crypttab in the generated initrd.img is empty

I cannot reproduce this using `dracut`, the entry is added correctly:
```
localhost:/home/dev # cat /etc/crypttab
cr-auto-1  UUID=28809213-2fcd-45db-9618-0227e407cefb  \0volcengine/cryptsetup/rootfs luks
localhost:/home/dev # lsinitrd -f etc/crypttab test.img
cr-auto-1 /dev/disk/by-uuid/28809213-2fcd-45db-9618-0227e407cefb \0volcengine/cryptsetup/rootfs luks
```

In any case, this would not be a systemd issue, since it is related to the content of the initrd.

**Comment by JustPlay** [comment]
> > and my /etc/crypttab is
> > ```
> > # <target name>        <source device>                <key file>        <options>
> > rootfs UUID=a5ba171f-d9a1-4874-b898-931ffd29a017 \0volcengine/cryptsetup/rootfs luks
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but when update-initramfs, i see the following warns:
> 
> `update-initramfs`? Sorry, what distro are you using, Debian/Ubuntu? SUSE does not provide `initramfs-tools`, we use [dracut](https://github.com/openSUSE/dracut) to generate initrds.
> 
> > ```
> > cryptsetup: WARNING: rootfs: keyfile 'volcengine/cryptsetup/rootfs' not found
> > cryptsetup: WARNING: Skipping root target rootfs: uses a key file
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and /cryptroot/crypttab in the generated initrd.img is empty
> 
> I cannot reproduce this using `dracut`, the entry is added correctly:
> 
> ```
> localhost:/home/dev # cat /etc/crypttab
> cr-auto-1  UUID=28809213-2fcd-45db-9618-0227e407cefb  \0volcengine/cryptsetup/rootfs luks
> localhost:/home/dev # lsinitrd -f etc/crypttab test.img
> cr-auto-1 /dev/disk/by-uuid/28809213-2fcd-45db-9618-0227e407cefb \0volcengine/cryptsetup/rootfs luks
> ```
> 
> In any case, this would not be a systemd issue, since it is related to the content of the initrd.

I am using ubuntu-22.04, thansk

**Comment by fbuihuu** [comment]
> I am using ubuntu-22.04, thanks

Then please ask your question to the Ubuntu channels, here it is dedicated to the integration of systemd on openSUSE distributions.
